### PR TITLE
#310 RsText maintains status code

### LINKED ISSUE #310: RsText overrides status code
Whatever you wrap into `RsText`, you get status 200.
```java
        MatcherAssert.assertThat(
            new RsPrint(
                new RsText(
                    new RsWithStatus(HttpURLConnection.HTTP_NOT_FOUND),
                    "something not found"
                )
            ).printHead(),
            Matchers.containsString(
                Integer.toString(HttpURLConnection.HTTP_NOT_FOUND)
            )
        );
```
Fails with:
````
java.lang.AssertionError: 
Expected: a string containing "404"
     but: was "HTTP/1.1 200 OK
Content-Length: 19
Content-Type: text/plain
```

### PR DESCRIPTION
**Pull request by mbarbieri**
Changed the RsText constructor to pass the response in the parameter instead of forcing a 200 response status.
Fixes #310

### CODE REVIEW

**Comment by davvd** [comment]
@mbarbieri Let me find a reviewer for this pull request, thanks for submitting it

**Comment by davvd** [comment]
@caarlos0 this pull request is for you,please review

File: src/test/java/org/takes/rs/RsTextTest.java [hunk 1]
```diff
@@ -58,4 +59,22 @@ public void makesPlainTextResponse() throws IOException {
...
+     */
+    @Test
+    public void makesTextResponseWithStatus() throws IOException {
+        MatcherAssert.assertThat(
+            new RsPrint(
+                new RsText(
+                    new RsWithStatus(HttpURLConnection.HTTP_NOT_FOUND),
+                    "something not found"
+                )
+            ).printHead(),
```
Comment (caarlos0) [inline src/test/java/org/takes/rs/RsTextTest.java]: @mbarbieri can't we get the status code and assert it instead of getting the head text?

Comment (mbarbieri) [inline src/test/java/org/takes/rs/RsTextTest.java]: @caarlos0 I don't know how... RsText doesn't expose the status code as of now. Please let me know if there is a way to do so...

Comment (caarlos0) [inline src/test/java/org/takes/rs/RsTextTest.java]: @mbarbieri I don't know either..

**Comment by caarlos0** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by mbarbieri** [comment]
@yegor256 was this a valid failure? Is it possible to retry and close the issue?

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor deploy

**Comment by elenavolokhova** [comment]
@caarlos0
According to our [quality rules](http://www.teamed.io/qa.html):
 > The code reviewer found at least three problems in the code.
 
 There were no issues found during review.
Please confirm that you will try to find at least three problems next time or ask to reassign CR to another reviewer.

**Comment by caarlos0** [comment]
@elenavolokhova Sure, I'll try

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@caarlos0 just added 10 mins to @elenavolokhova (for QA), payment ID is `58674545`; Much obliged! I have added **17 mins** to your account in payment "AP-2U045893D8193863G", 119 hours and 12 mins spent; you're getting extra minutes here (c=2); added +17 to your rating, now it is equal to [+2139](http://www.netbout.com/b/35095?open=rating)
