### PR TITLE
Use Cactoos from Body and remove guava from test

### LINKED ISSUE #804: Takes does not work well together with Cactoos
Using Takes together with Cactoos is not working well, as Takes building blocks are plain old Java objects.

I think it would be nice to integrate Takes and Cactoos, or at least replace Guava with it.
This way Takes can promote the usage of Cactoos.

What do you think?

### LINKED ISSUE #887: Body.java:41-45: Make Body extends Cactoos's Input and...
The puzzle `804-84fdf636` from #804 has to be resolved: 

https://github.com/yegor256/takes/blob/1d43de35261ec3d5a3ee11ce6f156e35a752131a/src/main/java/org/takes/rs/Body.java#L41-L45

The puzzle was created by Victor Noël on 24-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by Serranya**
This fixes #887

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#942](https://github.com/yegor256/takes/issues/942) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#942](https://github.com/yegor256/takes/issues/942) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2c7b08f5-74ac-41db-8c76-521e816acf08); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#942` already assigned to @fabriciofx, can't assign to @fabriciofx

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#942` already assigned to @fabriciofx, can't assign to @fabriciofx

**Comment by Serranya** [comment]
@fabriciofx Travis fails because of something else. I opened a bug report at https://github.com/yegor256/takes/issues/943

**Comment by Serranya** [comment]
@fabriciofx Please review again

File: src/test/java/org/takes/rs/BodyByteArrayTest.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+    /**
+     * Body.ByteArray can provide the expected input.
+     * @throws Exception If some problem inside.
+     */
+    @Test
+    public void returnsCorrectInputWithByteArray() throws Exception {
+        final byte[] bytes =
+            new Utf8String("ByteArray returnsCorrectInput!").asBytes();
+        MatcherAssert.assertThat(
+            "ByteArray doesn't provide correct bytes",
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyByteArrayTest.java]: @Serranya Please, add the name "body content" into the message to be more clear and specific. It's too much generic.

File: src/test/java/org/takes/rs/BodyStreamTest.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+    /**
+     * Body.Stream can provide the expected input.
+     * @throws Exception If some problem inside.
+     */
+    @Test
+    public void returnsCorrectInputWithStream() throws Exception {
+        final byte[] bytes =
+            new Utf8String("Stream returnsCorrectInput!").asBytes();
+        MatcherAssert.assertThat(
+            "Stream doesn't provide correct bytes",
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyStreamTest.java]: @Serranya The same here. See above.

File: src/test/java/org/takes/rs/BodyStreamTest.java [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+    /**
+     * Body.Stream can provide the expected length.
+     * @throws Exception If some problem inside.
+     */
+    @Test
+    public void returnsCorrectLengthWithStream() throws Exception {
+        final byte[] bytes =
+            new Utf8String("Stream returnsCorrectLength!").asBytes();
+        MatcherAssert.assertThat(
+            "Stream doesn't provide correct number of bytes",
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyStreamTest.java]: @Serranya The same here. See above.

File: src/test/java/org/takes/rs/BodyTempFileTest.java [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+    /**
+     * Body.TemFile can provide the expected input.
+     * @throws Exception If some problem inside.
+     */
+    @Test
+    public void returnsCorrectInputWithStream() throws Exception {
+        final byte[] bytes =
+            new Utf8String("Stream returnsCorrectInput!").asBytes();
+        MatcherAssert.assertThat(
+            "Stream doesn't provide correct bytes",
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyTempFileTest.java]: @Serranya The same here. See above.

File: src/test/java/org/takes/rs/BodyTempFileTest.java [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+    /**
+     * Body.TemFile can provide the expected length.
+     * @throws Exception If some problem inside.
+     */
+    @Test
+    public void returnsCorrectLengthWithTempFile() throws Exception {
+        final byte[] bytes =
+            new Utf8String("TempFile returnsCorrectLength!").asBytes();
+        MatcherAssert.assertThat(
+            "TempFile doesn't provide correct number of bytes",
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyTempFileTest.java]: @Serranya The same here. See above.

**Comment by fabriciofx** [comment]
@Serranya Please, check it again.

**Comment by Serranya** [comment]
@fabriciofx Please review again.

File: src/test/java/org/takes/rs/BodyUrlTest.java [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+ */
+public final class BodyUrlTest {
+
+    /**
+     * Body.URL can provide the expected input.
+     * @throws Exception If some problem inside.
+     */
+    @Test
+    public void returnsCorrectInputWithUrl() throws Exception {
+        final Path file = BodyUrlTest.createTempFile();
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyUrlTest.java]: @Serranya Please, use Cactoos' `TempFile` instead of this method.

File: src/test/java/org/takes/rs/BodyUrlTest.java [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+        }
+    }
+
+    /**
+     * Body.URL can provide the expected length.
+     * @throws Exception If some problem inside.
+     */
+    @Test
+    public void returnsCorrectLengthWithUrl() throws Exception {
+        final Path file = BodyUrlTest.createTempFile();
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyUrlTest.java]: @Serranya The same here. See above.

File: src/test/java/org/takes/rs/BodyUrlTest.java [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+            Files.deleteIfExists(file);
+        }
+    }
+
+    /**
+     * Creates a temporary file for testing purpose.
+     * @return A temporary file for the test.
+     * @throws IOException If the file could not be created
+     */
+    private static Path createTempFile() throws IOException {
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyUrlTest.java]: @Serranya Delete this method. Private methods are a complete mistake.

**Comment by fabriciofx** [comment]
@Serranya There is something wrong with Appveyor. Can you check it?

File: src/test/java/org/takes/rs/BodyByteArrayTest.java [hunk 9]
```diff
@@ -0,0 +1,69 @@
...
+/**
+ * Test case for {@link Body.ByteArray}.
+ *
+ * @since 1.15
+ */
+public final class BodyByteArrayTest {
+
+    /**
+     * Body.ByteArray can provide the expected input.
+     * @throws Exception If some problem inside.
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyByteArrayTest.java]: @Serranya please, fix here "if there is some problem inside".

File: src/test/java/org/takes/rs/BodyByteArrayTest.java [hunk 10]
```diff
@@ -0,0 +1,69 @@
...
+        MatcherAssert.assertThat(
+            "Body content of Body.ByteArray doesn't provide the correct bytes",
+            new BytesOf(new Body.ByteArray(bytes)).asBytes(),
+            new IsEqual<>(bytes)
+        );
+    }
+
+    /**
+     * Body.ByteArray can provide the expected length.
+     * @throws Exception If some problem inside.
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyByteArrayTest.java]: @Serranya please, fix here "if there is some problem inside".

File: src/test/java/org/takes/rs/BodyStreamTest.java [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+/**
+ * Test case for {@link Body.Stream}.
+ *
+ * @since 1.15
+ */
+public final class BodyStreamTest {
+
+    /**
+     * Body.Stream can provide the expected input.
+     * @throws Exception If some problem inside.
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyStreamTest.java]: @Serranya please, fix here "if there is some problem inside".

File: src/test/java/org/takes/rs/BodyStreamTest.java [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+            new BytesOf(
+                new Body.Stream(new InputOf(bytes).stream())
+            ).asBytes(),
+            new IsEqual<>(bytes)
+        );
+    }
+
+    /**
+     * Body.Stream can provide the expected length.
+     * @throws Exception If some problem inside.
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyStreamTest.java]: @Serranya please, fix here "if there is some problem inside".

File: src/test/java/org/takes/rs/BodyTempFileTest.java [hunk 13]
```diff
@@ -0,0 +1,73 @@
...
+/**
+ * Test case for {@link Body.TempFile}.
+ *
+ * @since 1.15
+ */
+public final class BodyTempFileTest {
+
+    /**
+     * Body.TemFile can provide the expected input.
+     * @throws Exception If some problem inside.
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyTempFileTest.java]: @Serranya please, fix here "if there is some problem inside".

File: src/test/java/org/takes/rs/BodyTempFileTest.java [hunk 14]
```diff
@@ -0,0 +1,73 @@
...
+            new BytesOf(
+                new Body.TempFile(new Body.ByteArray(bytes))
+            ).asBytes(),
+            new IsEqual<>(bytes)
+        );
+    }
+
+    /**
+     * Body.TemFile can provide the expected length.
+     * @throws Exception If some problem inside.
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyTempFileTest.java]: @Serranya please, fix here "if there is some problem inside".

File: src/test/java/org/takes/rs/BodyUrlTest.java [hunk 15]
```diff
@@ -0,0 +1,79 @@
...
+/**
+ * Test case for {@link Body.Url}.
+ *
+ * @since 1.15
+ */
+public final class BodyUrlTest {
+
+    /**
+     * Body.URL can provide the expected input.
+     * @throws Exception If some problem inside.
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyUrlTest.java]: @Serranya please, fix here "if there is some problem inside".

File: src/test/java/org/takes/rs/BodyUrlTest.java [hunk 16]
```diff
@@ -0,0 +1,79 @@
...
+                "Body content of Body.Url doesn't provide the correct bytes",
+                new BytesOf(input).asBytes(),
+                new IsEqual<>(body.asBytes())
+            );
+        }
+    }
+
+    /**
+     * Body.URL can provide the expected length.
+     * @throws Exception If some problem inside.
```
Comment (fabriciofx) [inline src/test/java/org/takes/rs/BodyUrlTest.java]: @Serranya please, fix here "if there is some problem inside".

**Comment by fabriciofx** [comment]
@paulodamaso WDYT? There is some problem with Appveyor CI, but I think this PR has nothing to do with it.

**Comment by paulodamaso** [comment]
@fabriciofx Actually looks like the problem is indeed caused by this PR, see the Appveyor log

**Comment by Serranya** [comment]
@fabriciofx I fixed the javadoc

**Comment by fabriciofx** [comment]
@Serranya ok, but according with @paulodamaso there is something wrong. Please, check why Appveyor CI fails .

**Comment by Serranya** [comment]
@fabriciofx @paulodamaso This is because of a problem with the way I use the TeeInput. See https://github.com/yegor256/cactoos/issues/1024 for more details.

**Comment by fabriciofx** [comment]
@Serranya ok, now it seems fine to me. Thanks!

**Comment by fabriciofx** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#942](https://github.com/yegor256/takes/issues/942) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by ypshenychka** [comment]
@Serranya Thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/takes/issues/942#issuecomment-455772785))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
